import Link from "next/link"
import { ArrowRight, BarChart3, Check, Globe2, LockKeyhole, ShieldCheck, Sparkles, TrendingUp, WalletCards } from "lucide-react"

const nav = (
  <header className="sticky top-0 z-20 border-b border-slate-200/80 bg-[#f8fafc]/90 backdrop-blur-md">
    <div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 lg:px-8">
      <Link href="/" className="flex items-center gap-2.5" aria-label="Portfolio X-Ray inicio">
        <span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#183b56] text-white"><BarChart3 className="h-5 w-5" /></span>
        <span className="text-[15px] font-bold tracking-tight text-[#102a43]">Portfolio X-Ray</span>
      </Link>
      <nav className="hidden items-center gap-7 text-sm text-slate-600 md:flex">
        <Link href="/es/que-es-un-xray-de-cartera" className="font-medium text-[#183b56]">Qué es un X-Ray</Link>
        <Link href="/es/como-funciona" className="hover:text-[#183b56]">Cómo funciona</Link>
        <Link href="/" className="hover:text-[#183b56]">Crea tu cartera</Link>
      </nav>
      <Link href="/" className="rounded-lg bg-[#2563eb] px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-[#1d4ed8]">Empezar gratis</Link>
    </div>
  </header>
)

const footer = <footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl flex-col gap-3 px-5 py-8 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between lg:px-8"><span>© {new Date().getFullYear()} Portfolio X-Ray</span><span>Información clara para decisiones más informadas.</span></div></footer>

const insights = [
  { icon: BarChart3, title: "Distribución de activos", text: "Descubre cuánto tienes realmente en acciones, bonos, efectivo y otras categorías." },
  { icon: Globe2, title: "Exposición geográfica", text: "Identifica países, regiones y mercados emergentes presentes en tu cartera." },
  { icon: TrendingUp, title: "Riesgo y rentabilidad", text: "Consulta volatilidad, Sharpe, alfa, beta y correlaciones cuando estén disponibles." },
  { icon: WalletCards, title: "Mayores posiciones", text: "Detecta la concentración real en empresas y bonos subyacentes." },
]

export function WhatIsXrayPage() {
  return <div className="min-h-screen bg-[#f8fafc] text-[#102a43]">{nav}<main>
    <section className="relative overflow-hidden border-b border-slate-200 bg-[#eef5f8]">
      <div className="mx-auto grid max-w-6xl gap-12 px-5 py-20 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:px-8 lg:py-28">
        <div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#b9d7dc] bg-white/70 px-3 py-1.5 text-xs font-semibold uppercase tracking-[.14em] text-[#216477]"><Sparkles className="h-3.5 w-3.5" /> Guía de inversión</div><h1 className="max-w-3xl text-4xl font-semibold leading-[1.08] tracking-[-.04em] sm:text-6xl">¿Qué es un <span className="text-[#2563eb]">X-Ray</span> de cartera?</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Mira más allá de los nombres de tus fondos. Entiende cómo está compuesta tu cartera de verdad, con una lectura clara de su diversificación, exposición y riesgo.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/" className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#2563eb] px-5 py-3.5 text-sm font-semibold text-white shadow-lg shadow-blue-900/10 hover:bg-[#1d4ed8]">Analizar mi cartera <ArrowRight className="h-4 w-4" /></Link><Link href="/es/como-funciona" className="inline-flex items-center justify-center rounded-lg border border-slate-300 bg-white px-5 py-3.5 text-sm font-semibold text-[#183b56] hover:bg-slate-50">Ver cómo funciona</Link></div><p className="mt-5 flex items-center gap-2 text-xs text-slate-500"><LockKeyhole className="h-3.5 w-3.5" /> Gratis, sin cuenta y sin compromisos</p></div>
        <div className="relative"><div className="absolute -inset-5 rounded-[2rem] bg-[#dcecf0] blur-2xl" /><div className="relative rounded-2xl border border-slate-200 bg-white p-5 shadow-xl shadow-[#183b56]/10"><div className="flex items-center justify-between border-b border-slate-100 pb-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-slate-400">Portfolio overview</p><p className="mt-1 font-semibold">Mi cartera global</p></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">Analizada</span></div><div className="grid grid-cols-2 gap-3 py-5"><div className="rounded-xl bg-[#eef5f8] p-4"><p className="text-xs text-slate-500">Renta variable</p><p className="mt-2 text-2xl font-semibold">72.4%</p><div className="mt-3 h-2 rounded-full bg-slate-200"><div className="h-2 w-[72%] rounded-full bg-[#2563eb]" /></div></div><div className="rounded-xl bg-[#f4f7f4] p-4"><p className="text-xs text-slate-500">Diversificación</p><p className="mt-2 text-2xl font-semibold">Amplia</p><div className="mt-3 flex gap-1"><i className="h-2 flex-1 rounded-full bg-[#183b56]" /><i className="h-2 flex-1 rounded-full bg-[#4e9aa0]" /><i className="h-2 flex-1 rounded-full bg-[#b9d7dc]" /><i className="h-2 flex-1 rounded-full bg-slate-200" /></div></div></div><div className="space-y-3 border-t border-slate-100 pt-4">{["Estados Unidos", "Europa", "Asia desarrollada"].map((item, i) => <div key={item} className="flex items-center justify-between text-sm"><span className="text-slate-600">{item}</span><span className="font-semibold">{["41.2%", "23.8%", "7.4%"][i]}</span></div>)}</div></div></div>
      </div>
    </section>
    <section className="mx-auto max-w-6xl px-5 py-20 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-widest text-[#2563eb]">Una visión completa</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Deja de mirar activos aislados.</h2><p className="mt-4 leading-7 text-slate-600">El Instant X-Ray™ de Morningstar abre cada fondo y agrega sus posiciones subyacentes para revelar la fotografía completa de tu inversión.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{insights.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#eef5f8] text-[#2563eb]"><Icon className="h-5 w-5" /></span><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></article>)}</div></section>
    <section className="bg-[#183b56] text-white"><div className="mx-auto grid max-w-6xl gap-12 px-5 py-20 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><p className="text-sm font-semibold uppercase tracking-widest text-[#9bd1d1]">Cómo leerlo</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">El informe responde las preguntas importantes.</h2></div><div className="grid gap-6 sm:grid-cols-2">{["¿Estoy realmente diversificado?", "¿Qué países y sectores pesan más?", "¿Dónde está mi concentración?", "¿Cuánto riesgo estoy asumiendo?"] .map((q) => <div key={q} className="flex gap-3 border-t border-white/15 pt-4"><Check className="mt-0.5 h-5 w-5 shrink-0 text-[#9bd1d1]" /><p className="text-lg text-slate-100">{q}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-3xl px-5 py-20 lg:px-8"><h2 className="text-3xl font-semibold tracking-tight">Preguntas frecuentes</h2><div className="mt-8 divide-y divide-slate-200">{[["¿Es gratis generar un X-Ray?","Sí. Puedes construir tu cartera y generar el informe sin crear una cuenta."],["¿Quién genera el PDF?","Portfolio X-Ray construye el enlace; el informe lo genera renta4banco usando la tecnología Instant X-Ray™ de Morningstar."],["¿Qué activos analiza?","Principalmente fondos UCITS, ETFs, ETCs y acciones. Los planes de pensiones, EPSV/PPSI y FIL no están pensados para este análisis."]].map(([q,a]) => <details key={q} className="group py-5"><summary className="cursor-pointer list-none pr-8 font-semibold marker:hidden">{q}<span className="float-right text-xl text-[#2563eb] transition group-open:rotate-45">+</span></summary><p className="mt-3 max-w-2xl leading-7 text-slate-600">{a}</p></details>)}</div><div className="mt-10 rounded-2xl bg-[#eef5f8] p-7"><h3 className="text-xl font-semibold">¿Quieres ver tu cartera con claridad?</h3><p className="mt-2 text-slate-600">Crea tu X-Ray gratis y descubre la composición real de tus inversiones.</p><Link href="/" className="mt-5 inline-flex items-center gap-2 font-semibold text-[#2563eb]">Crear mi cartera <ArrowRight className="h-4 w-4" /></Link></div></section>
  </main>{footer}</div>
}

const steps = [
  ["01", "Añade tus activos", "Introduce ISIN o ID de Morningstar para una coincidencia rápida y precisa. También puedes buscar por ticker o nombre."],
  ["02", "Define los pesos", "Reparte tu cartera por porcentaje hasta llegar al 100% o introduce importes para que calculemos los porcentajes automáticamente."],
  ["03", "Genera el X-Ray", "Pulsa el botón y obtén el enlace del informe Instant X-Ray™ generado a partir de tu cartera."],
  ["04", "Guarda y comparte", "Guarda tu composición, elige si es pública o privada y comparte el enlace con quien quieras."],
]

export function HowItWorksPage() {
  return <div className="min-h-screen bg-[#f8fafc] text-[#102a43]">{nav}<main>
    <section className="bg-[#183b56] text-white"><div className="mx-auto max-w-6xl px-5 py-20 lg:px-8 lg:py-28"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-widest text-[#9bd1d1]">En pocos minutos</p><h1 className="mt-5 text-4xl font-semibold leading-tight tracking-[-.04em] sm:text-6xl">Cómo funciona el generador de X-Ray de cartera</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-200">Construye una visión completa de tus inversiones, desde los activos que eliges hasta el informe final. Sin complicaciones y sin necesidad de crear una cuenta.</p><Link href="/" className="mt-9 inline-flex items-center gap-2 rounded-lg bg-[#2563eb] px-5 py-3.5 text-sm font-semibold text-white hover:bg-[#1d4ed8]">Empezar ahora <ArrowRight className="h-4 w-4" /></Link></div></div></section>
    <section className="mx-auto max-w-6xl px-5 py-20 lg:px-8"><div className="grid gap-5 lg:grid-cols-2">{steps.map(([number,title,text]) => <article key={number} className="group rounded-2xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="flex items-start justify-between"><span className="text-4xl font-semibold tracking-tight text-[#b9d7dc]">{number}</span><ArrowRight className="h-5 w-5 text-[#2563eb] transition group-hover:translate-x-1" /></div><h2 className="mt-8 text-2xl font-semibold">{title}</h2><p className="mt-3 max-w-md leading-7 text-slate-600">{text}</p></article>)}</div></section>
    <section className="border-y border-slate-200 bg-white"><div className="mx-auto grid max-w-6xl gap-12 px-5 py-20 lg:grid-cols-[.85fr_1.15fr] lg:px-8"><div><p className="text-sm font-semibold uppercase tracking-widest text-[#2563eb]">Elige tu forma de trabajar</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Flexibilidad sin perder el control.</h2><p className="mt-4 leading-7 text-slate-600">Tus importes son privados. Al compartir una cartera, otros solo ven los porcentajes, nunca las cifras absolutas.</p></div><div className="overflow-hidden rounded-2xl border border-slate-200"><div className="grid grid-cols-2 bg-[#eef5f8] text-sm font-semibold"><div className="p-4">Característica</div><div className="p-4">Tu cartera</div></div>{[["Modo porcentaje","Total hasta 100%"],["Modo importe","Cálculo automático"],["Visibilidad","Pública o privada"],["Importes","Solo tú los ves"]].map(([a,b]) => <div key={a} className="grid grid-cols-2 border-t border-slate-200 text-sm"><div className="p-4 text-slate-600">{a}</div><div className="p-4 font-medium">{b}</div></div>)}</div></div></section>
    <section className="mx-auto max-w-6xl px-5 py-20 lg:px-8"><div className="rounded-3xl bg-[#eef5f8] p-8 sm:p-12"><div className="max-w-2xl"><ShieldCheck className="h-9 w-9 text-[#2563eb]" /><h2 className="mt-5 text-3xl font-semibold tracking-tight">Una herramienta para entender, no para adivinar.</h2><p className="mt-4 leading-7 text-slate-600">El X-Ray organiza la información de tu cartera para que puedas tomar mejores decisiones con datos. El informe no constituye asesoramiento financiero.</p><div className="mt-7 flex flex-wrap gap-x-7 gap-y-3 text-sm font-medium text-[#183b56]"><span className="flex items-center gap-2"><Check className="h-4 w-4 text-emerald-600" /> Sin cuenta para empezar</span><span className="flex items-center gap-2"><Check className="h-4 w-4 text-emerald-600" /> Gratis</span><span className="flex items-center gap-2"><Check className="h-4 w-4 text-emerald-600" /> Enlace compartible</span></div><Link href="/" className="mt-8 inline-flex items-center gap-2 rounded-lg bg-[#2563eb] px-5 py-3.5 text-sm font-semibold text-white hover:bg-[#1d4ed8]">Crea tu cartera <ArrowRight className="h-4 w-4" /></Link></div></div></section>
  </main>{footer}</div>
}
